Fix bug in checking for uploads and downloads
SkynetLabs/ansible-playbooks pull request #182
Opened 2021-12-17 20:43 UTC by MSevey

# PULL REQUEST

## Overview
Added a condition to catch if the docker container is restarting when checking for uploads and downloads that are in progress.

2022-01-07 12:08 UTC, firyx requested changes

2022-01-07 12:08 UTC, firyx commented on playbooks/tasks/portal-health-check-disable.yml
> +      # is # the Module not loaded error. Otherwise we will continue on after the
```suggestion
      # is the Module not loaded error. Otherwise we will continue on after the
```

2022-01-07 12:08 UTC, firyx commented on playbooks/tasks/portal-health-check-disable.yml
> +      # is # the Module not loaded error. Otherwise we will continue on after the
```suggestion
      # is the Module not loaded error. Otherwise we will continue on after the
```

2022-01-07 16:46 UTC, firyx approved these changes

2022-01-10 23:51 UTC, kwypchlo approved these changes

2022-01-10 23:51 UTC, merged