fix bug in health-check disable
SkynetLabs/ansible-playbooks pull request #198
Opened 2022-01-12 21:47 UTC by MSevey

# PULL REQUEST

## Overview
Noticed a small edge case when disabling the health-check fails due to the container restarting. This shouldn't cause the ansible playbook to fail because the end result is that the health-check isn't running which is the goal.

## Example for Visual Changes

## Checklist
Review and complete the checklist to ensure that the PR is complete before assigned to an approver.
 - [ ] All new methods or updated methods have clear docstrings
 - [ ] Testing added or updated for new methods
 - [ ] Verify if any changes impact the WebPortal Health Checks
 - [ ] Approriate documentation updated
 - [ ] Changelog file created

## Issues Closed

2022-01-13 10:03 UTC, kwypchlo requested changes
I don't think it's ok to assume that is health-check is restarting then we're ok to proceed - if the issue was temporary, it will start up and server will be put back to load balancer while we assumed it was out. 

Why was health-check container restarting?

2022-01-14 21:08 UTC, MSevey commented
> I don't think it's ok to assume that is health-check is restarting then we're ok to proceed - if the issue was temporary, it will start up and server will be put back to load balancer while we assumed it was out.
> 
> Why was health-check container restarting?

That is valid that it could be a temporary hiccup. I think it in production though, the chances that this happens because of a fluke restart that happened to be timed with an ansible command is pretty small. 

I don't think I have seen a time where a docker service was restarting and corrected itself without intervention on our servers fwiw. 

I ran into this edge case when starting up a portal. The health-check container wasn't starting up along with a number of other containers.  I think this is what we would see the majority of the time. The container is going to be stuck in a restart cycle until the bug is fixed.

2022-01-18 16:28 UTC, firyx approved these changes

2022-01-18 17:55 UTC, kwypchlo approved these changes

2022-01-18 17:56 UTC, merged