do not prune current docker data
SkynetLabs/ansible-playbooks pull request #217
Opened 2022-02-08 15:29 UTC by kwypchlo

- completely drop pruning docker data **before** rebuilding containers - we want to leverage build cache to speed up the process
- **after** rebuilding, prune only docker data that is more than 4 hours old (arbitrary number but should be good enough) which means it will keep docker data that was produced during current build process

Originally we added strict pruning before and after because we were running out of disk space during deploys due to issues with cache, small disks on some machines, log files overflow etc. Also with every rebuild, docker data kept growing and I didn't know there was an option to prune just old data. I think we're in a quite good position to keep just current docker data now and it should significantly improve build times on deploys.

Let's test it @firyx :)

2022-02-08 16:57 UTC, MSevey requested changes
Now that it is just after, we can move it to a task to DRY up the code.

2022-02-08 16:57 UTC, firyx approved these changes

2022-02-09 12:45 UTC, firyx approved these changes

2022-02-10 11:44 UTC, kwypchlo commented
> Now that it is just after, we can move it to a task to DRY up the code.

@firyx added that in https://github.com/SkynetLabs/ansible-playbooks/pull/217/commits/bc3b89d42b6f619595741d8ad10b0946c1c73ff7

2022-02-11 02:04 UTC, MSevey approved these changes

2022-02-11 02:04 UTC, merged