Update portal ping documentation
SkynetLabs/ansible-playbooks pull request #249
Opened 2022-03-09 21:22 UTC by MSevey

# PULL REQUEST

## Overview
Minor Doc update for portal ping.

## Issues Closed

2022-03-10 12:22 UTC, ro-tex submitted a review, later dismissed

2022-03-10 15:40 UTC, firyx approved these changes

2022-03-10 15:42 UTC, firyx requested changes

2022-03-10 15:42 UTC, firyx commented on README.md
> +**NOTE** this playbook is a wrapper for the `ping` command line tool and uses
It's a wrapper for Ansible `ping` module, not `ping` command line tool.

`ping` CLI tool might be ok (IP of the server is accessible), but the portal might not be pingable from Ansible.

2022-03-11 12:56 UTC, firyx approved these changes

2022-03-15 10:58 UTC, ro-tex approved these changes

2022-03-15 10:58 UTC, merged