consolidate use of server, cluster, and portal domain
SkynetLabs/ansible-playbooks pull request #261
Opened 2022-03-18 16:06 UTC by MSevey

# PULL REQUEST

## Overview
This PR consolidates the use of all the domains and utilizes this update https://github.com/SkynetLabs/ansible-private-sample/blob/main/inventory/hosts.ini#L19

Now users can just define domains in the hosts.ini file and won't need define anything in LastPass ahead of time. 

## Example for Visual Changes

## Checklist
Review and complete the checklist to ensure that the PR is complete before assigned to an approver.
 - [ ] All new methods or updated methods have clear docstrings
 - [ ] Testing added or updated for new methods
 - [ ] Verify if any changes impact the WebPortal Health Checks
 - [ ] Approriate documentation updated
 - [ ] Changelog file created

## Issues Closed

2022-03-22 10:45 UTC, ro-tex reviewed
LGTM.

2022-03-22 10:46 UTC, ro-tex submitted a review, later dismissed

2022-03-22 11:16 UTC, firyx requested changes
Please look here and 1 message below:
https://discord.com/channels/542938080349519882/940952883782897695/955785804263866388

2022-03-24 09:37 UTC, firyx approved these changes

2022-03-24 15:44 UTC, ro-tex approved these changes

2022-03-24 15:44 UTC, merged