move portal modules outside of server config
SkynetLabs/ansible-playbooks pull request #264
Opened 2022-03-22 13:49 UTC by MSevey

# PULL REQUEST

## Overview
Update how backwards compatibility is handled with portal_modules. 

## Issues Closed

2022-03-22 14:25 UTC, firyx requested changes

2022-03-22 14:25 UTC, firyx commented on playbooks/group_vars/webportals.yml
> +  portal_modules: ""
Shouldn't we leave this out?

If we already have it in LastPass, this default will not be used.

If we do not have it, operator should define it in `hosts.ini` and we shouldn't pollute LastPass with default empty value anymore.

2022-03-24 09:34 UTC, firyx approved these changes

2022-03-24 15:44 UTC, ro-tex approved these changes

2022-03-24 16:32 UTC, ro-tex approved these changes

2022-03-25 12:44 UTC, firyx approved these changes

2022-03-25 12:47 UTC, merged