Add loading of custom config files in ansible-private
SkynetLabs/ansible-playbooks pull request #295
Opened 2022-04-22 19:00 UTC by MSevey

# PULL REQUEST

## Overview
Add the ability to load custom variable config files. These can be defined in hosts.ini

Included tasks for setup following and deploy.

## Example for Visual Changes

## Checklist
Review and complete the checklist to ensure that the PR is complete before assigned to an approver.
 - [x] All new methods or updated methods have clear docstrings
 - [x] Testing added or updated for new methods
 - [x] Verify if any changes impact the WebPortal Health Checks
 - [x] Approriate documentation updated
 - [x] Changelog file created

## Issues Closed

Closes #293

2022-04-25 08:04 UTC, ro-tex submitted a review, later dismissed

2022-04-25 08:22 UTC, firyx requested changes

2022-04-25 08:22 UTC, firyx commented on playbooks/portals-setup-following.yml
> +    - name: Load Custom Variable File
We need to load vars also e.g. in `portals-setup-initial` and basically in every playbook and play where we set `lastpass_required: True`.

We should be able to do it simply using `vars_file`:
https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#defining-variables-in-included-files-and-roles

```
  vars:
    lastpass_required: True
  vars_file:
    - "{{ common_vars_file | default(omit) }}"
    - "{{ custom_vars_file | default(omit) }}"
```

Note that e.g. `portals-setup-following` playbook consists from 4 plays, we need to set it on all 4 plays.
And while `default(omit)` should work we should test it works as expected with `vars_file`.

2022-04-26 07:09 UTC, firyx approved these changes

2022-04-26 07:12 UTC, peterjan approved these changes

2022-04-26 12:35 UTC, merged