Create logs dir to fix S3 backup
SkynetLabs/ansible-playbooks pull request #309
Opened 2022-05-10 10:43 UTC by firyx

# PULL REQUEST

## Overview

S3 backup cron job expects existing `skynet-webportal/logs` directory, which is missing by default.

This PR makes sure the `logs` directory is present.

## Example for Visual Changes

## Checklist
Review and complete the checklist to ensure that the PR is complete before assigned to an approver.
 - [x] All new methods or updated methods have clear docstrings
 - [x] Testing added or updated for new methods
 - [x] Verify if any changes impact the WebPortal Health Checks
 - [x] Approriate documentation updated
 - [x] Changelog file created

## Issues Closed

2022-05-10 11:36 UTC, kwypchlo requested changes
this should be built in into the backup script so it does not rely on ansible setting up the server

2022-05-10 12:41 UTC, firyx commented
> this should be built in into the backup script so it does not rely on ansible setting up the server

however we create the dir, it has to be created outside of backup script, because the `logs` dir must be created before the backup script runs:

https://github.com/SkynetLabs/skynet-webportal/blob/master/setup-scripts/support/crontab#L5
`44 5 * * * /home/user/skynet-webportal/scripts/backup-aws-s3.sh 1>>/home/user/skynet-webportal/logs/backup-aws-s3.log 2>>/home/user/skynet-webportal/logs/backup-aws-s3.log`

2022-05-10 19:46 UTC, MSevey approved these changes

2022-05-11 07:56 UTC, ro-tex approved these changes

2022-05-11 08:14 UTC, closed without merging