Add automation for cloudflare dns
SkynetLabs/ansible-playbooks pull request #356
Opened 2022-08-23 14:54 UTC by MSevey

# PULL REQUEST

## Overview
Add automation for cloudflare DNS.  Steps defined here:

https://github.com/SkynetLabs/skynet-webportal/blob/master/docker-compose.yml#L58

## Example for Visual Changes

## Checklist

- [ ] All git commits are signed. (REQUIRED)
- [ ] All new methods or updated methods have clear docstrings.
- [ ] Testing added or updated for new methods.
- [ ] Verified if any changes impact the WebPortal Health Checks.
- [ ] Appropriate documentation updated.
- [ ] Changelog file created.

## Issues Closed

2022-08-23 15:01 UTC, firyx requested changes

2022-08-23 15:01 UTC, firyx commented on playbooks/tasks/portal-role-task-certbot-custom-dns.yml
> +  when: dns_cloudflare_api_token is defined
Where is the secret value fo `dns_cloudflare_api_token` defined?
In hosts.ini or cluster yamls?
- this is not secured
=> it should be defined in secrets storage (cluster config) I think.

2022-08-23 15:40 UTC, firyx requested changes

2022-08-23 15:41 UTC, MSevey commented on playbooks/tasks/portal-role-task.yml
> +  when: webportal_common_config.aws_access_key is not defined and webportal_common_config.aws_access_key is not defined
no, that is handled in the task. The task will check for various custom configs. So we just check that the default AWS is not defined here.

2022-08-23 15:49 UTC, firyx approved these changes

2022-08-23 16:20 UTC, kwypchlo reviewed
while this is improvements since we only currently supported route53, I think this should be more generic implementation, most of the certbot dns plugins require an ini file

check https://eff-certbot.readthedocs.io/en/stable/using.html#dns-plugins

it does not make sense to implement plugin specific settings for each one of them right?

2022-08-24 12:34 UTC, MSevey commented
> while this is improvements since we only currently supported route53, I think this should be more generic implementation, most of the certbot dns plugins require an ini file
> 
> check https://eff-certbot.readthedocs.io/en/stable/using.html#dns-plugins
> 
> it does not make sense to implement plugin specific settings for each one of them right?

2022-08-24 12:39 UTC, MSevey commented
> it does not make sense to implement plugin specific settings for each one of them right?

it depends.

There are going to be pieces that can be generic, and there will be pieces that I'm sure will need to be specific. We can't know that unless we go through the set up for each and every option. That is not something that I'm going to do for this PR, and it is why I set up the code the way I did.

This structure allows for handling future DNS plugins either as separate specific cases, or can be updated to be generic as needed.

Happy to make a follow up issue for future reference but I think the effort for making this generic right now is not worth the benefit.

2022-08-24 12:46 UTC, kwypchlo approved these changes

2022-08-24 12:48 UTC, merged