Update .env template with PORTAL_DOMAIN and SERVER_DOMAIN
SkynetLabs/ansible-playbooks pull request #94
Opened 2021-09-01 12:26 UTC by firyx

2021-09-01 15:37 UTC, MSevey requested changes

2021-09-02 13:57 UTC, firyx commented on playbooks/templates/.env.j2
> +PORTAL_DOMAIN={{ webportal_cluster_config.portal_cluster_domain if (portal_cluster_id is defined) else webportal_server_config.domain_name }}
There is not 1-to-1 parity between LastPass/Ansible vars and `.env` vars.

In Ansible we have 2 variables:  
- `webportal_cluster_config.portal_cluster_domain` - this we set in LastPass
- `webportal_server_config.domain_name` - this is set automatically by Ansible and saved to LastPass by Ansible

From 2 above settings following `.env` vars are generated:
- `DOMAIN_NAME` - deprecated, not used anymore?
- `PORTAL_DOMAIN`
- `SERVER_DOMAIN`
- `PORTAL_NAME`
- `SSL_CERTIFICATE_STRING` - will be deprecated
- `SKYNET_PORTAL_API`
- `CR_IP`
- `CR_CLUSTER_NODES`
- `SKYNET_DASHBOARD_URL`
- `COOKIE_DOMAIN`

Most of the above `.env` vars above will end up having either `webportal_cluster_config.portal_cluster_domain` or `webportal_server_config.domain_name` value depending if the server is in a cluster or not.

In the upcoming `.env` generation PR I want to rename `webportal_server_config.domain_name` to just `webportal_server_config.domain`, but it needs synchronization between dev/testing the Ansible playbook branch & LastPass rename & `portal-setup-following` execution from `master` so I kept it for later.

2021-09-02 14:35 UTC, MSevey approved these changes

2021-09-02 15:22 UTC, kwypchlo approved these changes

2021-09-02 15:27 UTC, merged